export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';

export const FILTER_PRODUCTS_BY_ALL = 'FILTER_PRODUCTS_BY_ALL';
export const SORT_PRODUCTS = 'SORT_PRODUCTS';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const GET_LOCAL_CART = "GET_LOCAL_CART";
export const UPDATE_PRODUCT_COUNT = "UPDATE_PRODUCT_COUNT";

